### ISSUE TITLE
Attemping changing CPU Freq

### ISSUE THREAD

**Issue by aceday** [Rem01Gaming/origami_kernel_manager#1] opened 2024-08-03 01:29 UTC
When i use your latest update is more confused until 2nd or 3rd run.

When switching freq in 1st attempt.

CPU > Max Freq > Little > Not appeared (So i enter again) ... But in Big is appeared in Little CPU Freq.

Attempt # 2:
try again go to Little it appears all Big CPU Freq, and the Big appears to all Little CPU Freq.

CPU Used: MT6765

RFS: Your 2nd from latest version everything works for me, except swapped BIG and LITTLE label, but i m still using it.

**Comment by Rem01Gaming** [comment] 2024-08-03 01:36
Weird, I'm not sure but it may caused by ae605d3240b492885e79b6402d55b869116b6441, try to revert it and reinstall using make method.
Lemme know if this fix this issue

**Comment by Rem01Gaming** [comment] 2024-08-03 23:14
Should fixed on 10d7f7884dbd8ea9367eb8b9ec36573654c3b337

**Comment by aceday** [comment] 2024-08-05 17:43
Yeah, its working, but Big and Little still not swapped.

Example:
Little side - max is 2.3GHz
Big side - max is 1.8GHz

Where part is it swapped? CPU Info freqs and Chaging CPU Freq too.

**Comment by Rem01Gaming** [comment] 2024-08-05 22:22
Hmm it's need more debugging, can you send ss of `/sys/devices/system/cpu/cpufreq/policy*/scaling_available_frequencies` (yes all policy* folders)
Also run `sudo bash -x /data/data/com.termux/files/usr/share/origami-kernel/init_run.sh >/sdcard/init_run_output.txt` and send the file here

**Comment by aceday** [comment] 2024-08-06 02:35
Here

![Screenshot_20240806-103329_Termux](https://github.com/user-attachments/assets/fc49d2f0-c4ba-4903-8882-8aa9aa9c29de)

[init_run_output.txt](https://github.com/user-attachments/files/16504524/init_run_output.txt)

**Comment by Rem01Gaming** [comment] 2024-08-06 02:40
>
> [init_run_output.txt](https://github.com/user-attachments/files/16504524/init_run_output.txt)

Something's wrong, log file should look like this
![Screenshot_20240806-093709_Termux_Monet](https://github.com/user-attachments/assets/fcdb04b6-0dbe-4a1a-891c-dcc1e7553b6a)

**Comment by aceday** [comment] 2024-08-06 02:48
The output print itself on my terminal so i put from > to >> ..



Here


[init_run_output.txt](https://github.com/user-attachments/files/16504637/init_run_output.txt)

**Comment by Rem01Gaming** [comment] 2024-08-06 02:56
![20240806_095206](https://github.com/user-attachments/assets/324e0b8a-3219-4f81-9573-a9c59f2da70d)
![Screenshot_20240806-095356_QuickEdit+](https://github.com/user-attachments/assets/39e1f40e-f51a-4b97-8972-3e023e5788bb)

`git pull` and reinstall should fix this

**Comment by Rem01Gaming** [comment] 2024-08-06 02:58
Previously I said `Weird, I'm not sure but it may caused by ae605d3`
I take my words back :v it caused by 4d6cc826580772d8dcad52b364221daf0f281e78

**Comment by aceday** [comment] 2024-08-06 03:01
Yep, its fixed now and corrected assigned freq.

**Comment by Rem01Gaming** [comment] 2024-08-06 03:02
👍

**Closed as completed by Rem01Gaming** 2024-08-06 03:02 UTC
